site_name: mitgcm_utils
repo_name: prajeeshag/mitgcm_utils
repo_url: https://github.com/prajeeshag/mitgcm_utils
theme:
    name: readthedocs
    highlightjs: true

nav:
    - Home: index.md
    - Boundary conditions: boundary.md
    - Initial conditions: initial.md
    - External forcings: forcing.md
    - Grid: grid.md
    - Bathymetry: bathy.md

plugins:

markdown_extensions:
    # Python Markdown
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - mkdocs-click
    - toc:
          permalink: true

    # Python Markdown Extensions
    # - pymdownx.arithmatex:
    #       generic: true
    # - pymdownx.betterem:
    #       smart_enable: all
    # - pymdownx.caret
    # - pymdownx.details
    # - pymdownx.emoji:
    #       emoji_index: !!python/name:material.extensions.emoji.twemoji
    #       emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.inlinehilite
    # - pymdownx.keys
    # - pymdownx.mark
    # - pymdownx.smartsymbols
    # - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    # - pymdownx.tasklist:
    #       custom_checkbox: true
    # - pymdownx.tilde